spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC
    username: ecommerce_user
    password: ecommerce123

  jpa:
    hibernate:
      ddl-auto: validate # Usar validate pois teremos dump.sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE